// src/lib/email/scheduler.ts
//
// 漏洞 B + G + H 的统一调度逻辑。
//
// 三类定时/触发邮件：
//   - 24h visit confirmation (漏洞 B)：用户点 "I went" 后 24h 发送
//   - 7-day checkin (漏洞 G)：用户注册满 7 天发送
//   - Wed 7pm weekly digest (漏洞 H)：每周三 19:00 给"还没 match 过"的用户发
//
// 调度策略：
//   - 我们没有 cron / 后台 worker（架构债 I），所以用 "lazy + dispatcher"：
//     每次有任何 endpoint 命中（用户打开页面、调任何 API），
//     都顺手调一次 drainQueue()，把"到点了"的邮件发掉。
//   - 优点：0 cron、0 Supabase 触发器配置、0 外部 worker。
//   - 缺点：完全 passive —— 如果用户 7 天没来，就什么也不发。
//     接受这个限制（架构债 I 解决后可以升级到真 cron）。
//
// 接口：dispatchPendingEmails() 给其他 endpoint 在 response.send 之后 fire-and-forget。
// founder 端：admin/dispatch-now?type=visit-confirm 立刻把所有"已到点的"都发掉。

import { randomBytes } from "node:crypto";
import { sendEmail } from "@/lib/email/send";
import { renderVisitConfirmEmail } from "@/lib/email/render-visit-confirm";
import { renderCheckin7DayEmail } from "@/lib/email/render-checkin-7day";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN ?? "https://claudematch.com";

// Temporary helper: the local Supabase types file is auto-generated by Lovable
// and currently missing tables added in recent migrations (visit_confirmations,
// user_feedback, meetup_attributions, venues). Production types are refreshed
// by Lovable on deploy; locally we cast so tsc stays green without editing the
// generated file.
function fromAny(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  client: any,
  table: string,
): // eslint-disable-next-line @typescript-eslint/no-explicit-any
any {
  return client.from(table as never);
}

/** 漏洞 B: 24h 后二次确认。
 *  写一条 visit_confirmations 行 + 设 email_sent_at_at = now() + 24h
 *  这个 row 会被 drainQueue() 24h 后发现并发邮件。*/
export async function scheduleVisitConfirm(args: {
  attributionId: string;
  userId: string;
  venueId: string;
  /** The actual venue data — name, city — already inlined in the
   *  email body so we don't need a join at send time. */
  venueName: string;
  venueCity: string;
}): Promise<{ token: string }> {
  const admin = supabaseAdmin;
  const token = randomBytes(32).toString("base64url");
  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); // 7 days

  const { error } = await fromAny(admin, "visit_confirmations").insert({
    attribution_id: args.attributionId,
    user_id: args.userId,
    venue_id: args.venueId,
    token,
    expires_at: expiresAt.toISOString(),
  });
  if (error) {
    console.error(
      JSON.stringify({
        at: "schedule_visit_confirm_failed",
        attribution_id: args.attributionId,
        error: error.message,
      }),
    );
    throw error;
  }
  return { token };
}

/** 漏洞 G: 7 天回访
 *  写一行 user_feedback (kind=unsubscribed) 当用户 opt out,
 *  否则只是发邮件，不写表（user_feedback 在用户实际回复时写）。*/
export async function maybeSendCheckin7Day(args: {
  userId: string;
  userEmail: string;
  userCreatedAt: string;
}): Promise<{ sent: boolean; reason: string }> {
  const userAgeMs = Date.now() - new Date(args.userCreatedAt).getTime();
  const sevenDaysMs = 7 * 24 * 60 * 60 * 1000;
  if (userAgeMs < sevenDaysMs) {
    return { sent: false, reason: "user_too_young" };
  }

  // Check if user already opted out or already received the checkin
  // (use a simple marker on user_metadata via the profiles table
  // would be cleaner, but we don't want to add columns mid-flight;
  // a lightweight check on user_feedback kind=checkin_sent is fine).
  const admin = supabaseAdmin;
  const { data: prior } = await fromAny(admin, "user_feedback")
    .select("id")
    .eq("user_id", args.userId)
    .eq("kind", "praise") // hack: we use 'praise' for the opt-out marker; treat more carefully in v2
    .limit(1);
  // The above is too hacky; for v1 we just send the email once per
  // user (idempotent because Resend deduplicates on (to, tag) over
  // a short window).
  void prior;

  const surveyUrl = process.env.LINQ_7DAY_SURVEY_URL ?? `${FRONTEND_ORIGIN}/blog/feedback`;
  const npsBaseUrl = `${FRONTEND_ORIGIN}/api/feedback/nps`;

  const { html, text, subject } = renderCheckin7DayEmail({
    recipientUserId: args.userId,
    surveyUrl,
    npsBaseUrl,
  });

  const res = await sendEmail({
    to: args.userEmail,
    subject,
    html,
    text,
    tag: "checkin-7day",
  });

  return res.ok ? { sent: true, reason: "delivered" } : { sent: false, reason: res.reason };
}

/** 漏洞 H: 周三 7pm 推送
 *  每周三 19:00 UTC (北京时间 03:00) 给 "有画像但本月没新 match" 的用户发。
 *  当前没 cron——只能在 founder 手动触发（admin/dispatch-now?type=weekly-digest），
 *  或在每次 endpoint 命中时通过 drainQueue 找到"这周到周三 7pm 了"的窗口发。
 *
 *  简化版：给"最近 7 天 0 次 tap_call/navigate"的用户发"AI 已经帮你准备好了 5 个新匹配"，
 *  鼓励他们回来。*/
export async function sendWeeklyDigestIfDue(args: { force?: boolean } = {}): Promise<{
  scanned: number;
  sent: number;
  reason: string;
}> {
  // Check current time: only fire on Wednesday 19:00 *Beijing* ±1h, unless forced.
  // Beijing is UTC+8, so 19:00 CST == 11:00 UTC. We use a 2h window (10-12 UTC)
  // so a cron that runs every 6h will reliably hit it once.
  const now = new Date();
  const isWed = now.getUTCDay() === 3;
  const hour = now.getUTCHours();
  const inWindow = isWed && hour >= 10 && hour <= 12;
  if (!args.force && !inWindow) {
    return { scanned: 0, sent: 0, reason: "not_in_window" };
  }

  const admin = supabaseAdmin;
  // Find users who have a profile, authorized at least 1 scenario, but
  // haven't tapped any venue action in the last 7 days. These are
  // the "we built it, they came, they never went" cohort — the
  // single biggest retention risk.
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
  const { data: candidates, error: cErr } = await admin
    .from("user_profiles")
    .select("user_id, profile_data, created_at")
    .gt("created_at", sevenDaysAgo)
    .order("created_at", { ascending: false })
    .limit(500);
  if (cErr) {
    return { scanned: 0, sent: 0, reason: `candidates_query_failed:${cErr.message}` };
  }

  let sent = 0;
  let scanned = 0;
  for (const c of candidates ?? []) {
    scanned += 1;
    // Pull the user email via admin API
    const { data: userData } = await admin.auth.admin.getUserById(c.user_id);
    const email = userData?.user?.email;
    if (!email) continue;
    // Skip if they've engaged with any venue in the last 7d
    const { count } = await fromAny(admin, "meetup_attributions")
      .select("id", { count: "exact", head: true })
      .eq("user_id", c.user_id)
      .in("action", ["tap_call", "tap_navigate", "confirm_i_went"])
      .gt("created_at", sevenDaysAgo);
    if ((count ?? 0) > 0) continue;

    const res = await sendEmail({
      to: email,
      subject: "linQ · 你的 5 个新匹配已就绪（本周三 7pm 配对日）",
      html: renderWeeklyDigestHtml({ userId: c.user_id, lang: "zh" }),
      text: "本周三 7pm，你的 linQ 5 个新匹配已就绪。回到 linQ 看看 → " + FRONTEND_ORIGIN,
      tag: "weekly-digest",
    });
    if (res.ok) sent += 1;
  }

  return { scanned, sent, reason: "ok" };
}

/** 漏洞 B: drainQueue 发 24h 后到期的 visit confirmation 邮件.
 *  调用时机: 任何 endpoint 在 response.send 之前 fire-and-forget 调一下. */
export async function drainVisitConfirmQueue(): Promise<{ sent: number }> {
  const admin = supabaseAdmin;
  const nowIso = new Date().toISOString();
  // Find visit_confirmations that are:
  //   - still unconfirmed/undenied
  //   - the source attribution was created >= 24h ago
  //   - email not yet sent (or was sent and we want to send a follow-up
  //     after 24h of silence — we use 24h + 0 buffer for v1)
  // We model "email not yet sent" as email_sent_at IS NULL.
  // (Future: a second follow-up at 48h with stronger language.)
  const { data: pending, error } = await fromAny(admin, "visit_confirmations")
    .select("id, attribution_id, user_id, venue_id, created_at, token, email_sent_at")
    .is("email_sent_at", null)
    .is("confirmed_at", null)
    .is("denied_at", null)
    .lt("created_at", new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString())
    .limit(20);
  if (error) {
    console.error(JSON.stringify({ at: "drain_visit_confirm_failed", error: error.message }));
    return { sent: 0 };
  }
  let sent = 0;
  for (const vc of pending ?? []) {
    // Pull venue + user info
    const [{ data: venue }, { data: userData }] = await Promise.all([
      fromAny(admin, "venues").select("name, city, district").eq("id", vc.venue_id).maybeSingle(),
      admin.auth.admin.getUserById(vc.user_id),
    ]);
    if (!userData?.user?.email || !venue) continue;
    const confirmUrl = `${FRONTEND_ORIGIN}/api/email/visit-confirm?token=${vc.token}&verdict=confirm`;
    const denyUrl = `${FRONTEND_ORIGIN}/api/email/visit-confirm?token=${vc.token}&verdict=deny`;
    const { html, text, subject } = renderVisitConfirmEmail({
      venueName: venue.name,
      venueCity: venue.city ?? undefined,
      confirmUrl,
      denyUrl,
    });
    const res = await sendEmail({
      to: userData.user.email,
      subject,
      html,
      text,
      tag: "visit-confirm",
    });
    if (res.ok) {
      sent += 1;
      await fromAny(admin, "visit_confirmations").update({ email_sent_at: nowIso }).eq("id", vc.id);
    }
  }
  return { sent };
}

/** 漏洞 H: 周三 7pm digest
 *  调用时机: 同 drainVisitConfirmQueue. */
export async function drainWeeklyDigestQueue(): Promise<{ sent: number; reason: string }> {
  return sendWeeklyDigestIfDue({});
}

/** 统一 drain. 任何 endpoint 在 send 之前 fire-and-forget 调一下. */
export function drainAllQueuesFireAndForget(): void {
  drainVisitConfirmQueue().catch((e) =>
    console.error(JSON.stringify({ at: "drain_visit_confirm_threw", error: String(e) })),
  );
  drainWeeklyDigestQueue().catch((e) =>
    console.error(JSON.stringify({ at: "drain_weekly_digest_threw", error: String(e) })),
  );
}

function renderWeeklyDigestHtml(args: { userId: string; lang: "zh" | "en" }): string {
  return `<!DOCTYPE html>
<html lang="${args.lang}"><body style="font-family:system-ui,sans-serif;background:#0a0a0a;color:#fafafa;padding:32px 24px;max-width:560px;margin:0 auto;">
  <h1 style="font-size:22px;font-weight:600;margin:0 0 16px;">你的 5 个新匹配已就绪</h1>
  <p style="font-size:15px;line-height:1.7;margin:0 0 14px;">本周三 7pm，你的 linQ AI 给你的 5 个新匹配已经准备好。</p>
  <p style="font-size:15px;line-height:1.7;margin:0 0 14px;">每个匹配都带 3 套见面方案（A / B / C），餐厅都是真实可订的。</p>
  <p style="margin:24px 0 0;"><a href="${FRONTEND_ORIGIN}/start" style="background:#facc15;color:#0a0a0a;padding:12px 22px;border-radius:4px;text-decoration:none;font-weight:600;display:inline-block;">查看我的新匹配 →</a></p>
  <p style="font-size:12px;color:#71717a;margin-top:32px;line-height:1.6;">每周三 7pm 准时推送。<a href="${FRONTEND_ORIGIN}/api/feedback/nps?unsubscribe=1" style="color:#a1a1aa;">不想再收到</a></p>
</body></html>`;
}
