import { createFileRoute } from "@tanstack/react-router";
import { json, preflight, requireUser } from "@/lib/api/_helpers.server";

/**
 * POST /api/ai/meet-plan
 * Body: { match_id: string }
 * Generates a placeholder meet-up plan and persists it to `meet_plans`.
 * Only the owner of the match can create a plan for it (enforced by RLS).
 */
const PLACES = ["Blue Bottle Coffee", "Equator Coffees", "Verve Coffee", "Sightglass"];
const ACTIVITIES = ["coffee & walk", "rooftop drinks", "weekend brunch", "art gallery visit"];
const ICEBREAKERS = [
  "What's something you got unreasonably into this year?",
  "If you could teach a 1-hour class on anything, what would it be?",
  "What's a project you'd build if money wasn't a constraint?",
];

function pick<T>(arr: T[], seed: string, salt: number) {
  const h = Array.from(seed).reduce((a, c) => (a * 31 + c.charCodeAt(0)) >>> 0, salt);
  return arr[h % arr.length];
}

export const Route = createFileRoute("/api/ai/meet-plan")({
  server: {
    handlers: {
      OPTIONS: async () => preflight(),
      POST: async ({ request }) => {
        const auth = await requireUser(request);
        if ("error" in auth) return auth.error;
        const { userId, supabase } = auth;

        let body: unknown;
        try {
          body = await request.json();
        } catch {
          return json({ error: "Invalid JSON body" }, { status: 400 });
        }
        const match_id = (body as { match_id?: unknown })?.match_id;
        if (typeof match_id !== "string" || match_id.length < 8) {
          return json({ error: "match_id is required" }, { status: 400 });
        }

        const { data: match, error: mErr } = await supabase
          .from("matches")
          .select("id, user_id, matched_user_id, scenario")
          .eq("id", match_id)
          .maybeSingle();

        if (mErr) return json({ error: mErr.message }, { status: 500 });
        if (!match || match.user_id !== userId) {
          return json({ error: "Match not found" }, { status: 404 });
        }

        const next = new Date();
        next.setUTCDate(next.getUTCDate() + 3);
        next.setUTCHours(19, 0, 0, 0);

        const plan_content = {
          version: "v1",
          scenario: match.scenario,
          when: next.toISOString(),
          where: pick(PLACES, match.id, 7),
          activity: pick(ACTIVITIES, match.id, 13),
          icebreakers: [pick(ICEBREAKERS, match.id, 3), pick(ICEBREAKERS, match.id, 11)],
          note: "Plan generated by linQ. Confirm with the other side before showing up.",
        };

        const { data, error } = await supabase
          .from("meet_plans")
          .insert({ match_id, plan_content })
          .select("*")
          .single();

        if (error) return json({ error: error.message }, { status: 500 });
        return json({ data, message: "Meet-up plan generated" });
      },
    },
  },
});