/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ForRestaurantsRouteImport } from './routes/for-restaurants'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthWxCallbackRouteImport } from './routes/auth/wx-callback'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiMatchRouteImport } from './routes/api/match'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiAuthorizeRouteImport } from './routes/api/authorize'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as ApiVenuesTrackRouteImport } from './routes/api/venues/track'
import { Route as ApiVenuesOnboardRouteImport } from './routes/api/venues/onboard'
import { Route as ApiVenuesLookupRouteImport } from './routes/api/venues/lookup'
import { Route as ApiUserSetCityRouteImport } from './routes/api/user/set-city'
import { Route as ApiUserMeRouteImport } from './routes/api/user/me'
import { Route as ApiReferralsClaimRouteImport } from './routes/api/referrals/claim'
import { Route as ApiMatchIdRouteImport } from './routes/api/match/$id'
import { Route as ApiFeedbackReportRouteImport } from './routes/api/feedback/report'
import { Route as ApiFeedbackQualityRouteImport } from './routes/api/feedback/quality'
import { Route as ApiFeedbackPatternRouteImport } from './routes/api/feedback/pattern'
import { Route as ApiFeedbackNpsRouteImport } from './routes/api/feedback/nps'
import { Route as ApiFeedbackMeetRouteImport } from './routes/api/feedback/meet'
import { Route as ApiEmailVisitConfirmRouteImport } from './routes/api/email/visit-confirm'
import { Route as ApiCronForceWeeklyDigestRouteImport } from './routes/api/cron/force-weekly-digest'
import { Route as ApiCronDrainRouteImport } from './routes/api/cron/drain'
import { Route as ApiAiMeetPlanRouteImport } from './routes/api/ai/meet-plan'
import { Route as ApiAiMatchRouteImport } from './routes/api/ai/match'
import { Route as ApiAiInterviewQuestionsRouteImport } from './routes/api/ai/interview-questions'
import { Route as ApiAiGenerateProfileRouteImport } from './routes/api/ai/generate-profile'
import { Route as ApiAdminReconciliationRouteImport } from './routes/api/admin/reconciliation'
import { Route as AuthenticatedMatchIdRouteImport } from './routes/_authenticated/match.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiVenuesMerchantDashboardRouteImport } from './routes/api/venues/merchant/dashboard'
import { Route as ApiAuthWechatUnbindRouteImport } from './routes/api/auth/wechat/unbind'
import { Route as ApiAuthWechatStartRouteImport } from './routes/api/auth/wechat/start'
import { Route as ApiAuthWechatCallbackRouteImport } from './routes/api/auth/wechat/callback'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRestaurantsRoute = ForRestaurantsRouteImport.update({
  id: '/for-restaurants',
  path: '/for-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthWxCallbackRoute = AuthWxCallbackRouteImport.update({
  id: '/wx-callback',
  path: '/wx-callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchRoute = ApiMatchRouteImport.update({
  id: '/api/match',
  path: '/api/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorizeRoute = ApiAuthorizeRouteImport.update({
  id: '/api/authorize',
  path: '/api/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVenuesTrackRoute = ApiVenuesTrackRouteImport.update({
  id: '/api/venues/track',
  path: '/api/venues/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVenuesOnboardRoute = ApiVenuesOnboardRouteImport.update({
  id: '/api/venues/onboard',
  path: '/api/venues/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVenuesLookupRoute = ApiVenuesLookupRouteImport.update({
  id: '/api/venues/lookup',
  path: '/api/venues/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSetCityRoute = ApiUserSetCityRouteImport.update({
  id: '/api/user/set-city',
  path: '/api/user/set-city',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserMeRoute = ApiUserMeRouteImport.update({
  id: '/api/user/me',
  path: '/api/user/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsClaimRoute = ApiReferralsClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ApiReferralsRoute,
} as any)
const ApiMatchIdRoute = ApiMatchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMatchRoute,
} as any)
const ApiFeedbackReportRoute = ApiFeedbackReportRouteImport.update({
  id: '/api/feedback/report',
  path: '/api/feedback/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackQualityRoute = ApiFeedbackQualityRouteImport.update({
  id: '/api/feedback/quality',
  path: '/api/feedback/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackPatternRoute = ApiFeedbackPatternRouteImport.update({
  id: '/api/feedback/pattern',
  path: '/api/feedback/pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackNpsRoute = ApiFeedbackNpsRouteImport.update({
  id: '/api/feedback/nps',
  path: '/api/feedback/nps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackMeetRoute = ApiFeedbackMeetRouteImport.update({
  id: '/api/feedback/meet',
  path: '/api/feedback/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailVisitConfirmRoute = ApiEmailVisitConfirmRouteImport.update({
  id: '/api/email/visit-confirm',
  path: '/api/email/visit-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronForceWeeklyDigestRoute =
  ApiCronForceWeeklyDigestRouteImport.update({
    id: '/api/cron/force-weekly-digest',
    path: '/api/cron/force-weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronDrainRoute = ApiCronDrainRouteImport.update({
  id: '/api/cron/drain',
  path: '/api/cron/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMeetPlanRoute = ApiAiMeetPlanRouteImport.update({
  id: '/api/ai/meet-plan',
  path: '/api/ai/meet-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMatchRoute = ApiAiMatchRouteImport.update({
  id: '/api/ai/match',
  path: '/api/ai/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInterviewQuestionsRoute = ApiAiInterviewQuestionsRouteImport.update({
  id: '/api/ai/interview-questions',
  path: '/api/ai/interview-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateProfileRoute = ApiAiGenerateProfileRouteImport.update({
  id: '/api/ai/generate-profile',
  path: '/api/ai/generate-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReconciliationRoute = ApiAdminReconciliationRouteImport.update({
  id: '/api/admin/reconciliation',
  path: '/api/admin/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMatchIdRoute = AuthenticatedMatchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMatchRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVenuesMerchantDashboardRoute =
  ApiVenuesMerchantDashboardRouteImport.update({
    id: '/api/venues/merchant/dashboard',
    path: '/api/venues/merchant/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthWechatUnbindRoute = ApiAuthWechatUnbindRouteImport.update({
  id: '/api/auth/wechat/unbind',
  path: '/api/auth/wechat/unbind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWechatStartRoute = ApiAuthWechatStartRouteImport.update({
  id: '/api/auth/wechat/start',
  path: '/api/auth/wechat/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWechatCallbackRoute = ApiAuthWechatCallbackRouteImport.update({
  id: '/api/auth/wechat/callback',
  path: '/api/auth/wechat/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/founder': typeof FounderRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/match': typeof AuthenticatedMatchRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/start': typeof AuthenticatedStartRoute
  '/api/authorize': typeof ApiAuthorizeRoute
  '/api/login': typeof ApiLoginRoute
  '/api/match': typeof ApiMatchRouteWithChildren
  '/api/referrals': typeof ApiReferralsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/auth/wx-callback': typeof AuthWxCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$id': typeof AuthenticatedMatchIdRoute
  '/api/admin/reconciliation': typeof ApiAdminReconciliationRoute
  '/api/ai/generate-profile': typeof ApiAiGenerateProfileRoute
  '/api/ai/interview-questions': typeof ApiAiInterviewQuestionsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/meet-plan': typeof ApiAiMeetPlanRoute
  '/api/cron/drain': typeof ApiCronDrainRoute
  '/api/cron/force-weekly-digest': typeof ApiCronForceWeeklyDigestRoute
  '/api/email/visit-confirm': typeof ApiEmailVisitConfirmRoute
  '/api/feedback/meet': typeof ApiFeedbackMeetRoute
  '/api/feedback/nps': typeof ApiFeedbackNpsRoute
  '/api/feedback/pattern': typeof ApiFeedbackPatternRoute
  '/api/feedback/quality': typeof ApiFeedbackQualityRoute
  '/api/feedback/report': typeof ApiFeedbackReportRoute
  '/api/match/$id': typeof ApiMatchIdRoute
  '/api/referrals/claim': typeof ApiReferralsClaimRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/user/set-city': typeof ApiUserSetCityRoute
  '/api/venues/lookup': typeof ApiVenuesLookupRoute
  '/api/venues/onboard': typeof ApiVenuesOnboardRoute
  '/api/venues/track': typeof ApiVenuesTrackRoute
  '/api/auth/wechat/callback': typeof ApiAuthWechatCallbackRoute
  '/api/auth/wechat/start': typeof ApiAuthWechatStartRoute
  '/api/auth/wechat/unbind': typeof ApiAuthWechatUnbindRoute
  '/api/venues/merchant/dashboard': typeof ApiVenuesMerchantDashboardRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/founder': typeof FounderRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/match': typeof AuthenticatedMatchRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/start': typeof AuthenticatedStartRoute
  '/api/authorize': typeof ApiAuthorizeRoute
  '/api/login': typeof ApiLoginRoute
  '/api/match': typeof ApiMatchRouteWithChildren
  '/api/referrals': typeof ApiReferralsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/auth/wx-callback': typeof AuthWxCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/match/$id': typeof AuthenticatedMatchIdRoute
  '/api/admin/reconciliation': typeof ApiAdminReconciliationRoute
  '/api/ai/generate-profile': typeof ApiAiGenerateProfileRoute
  '/api/ai/interview-questions': typeof ApiAiInterviewQuestionsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/meet-plan': typeof ApiAiMeetPlanRoute
  '/api/cron/drain': typeof ApiCronDrainRoute
  '/api/cron/force-weekly-digest': typeof ApiCronForceWeeklyDigestRoute
  '/api/email/visit-confirm': typeof ApiEmailVisitConfirmRoute
  '/api/feedback/meet': typeof ApiFeedbackMeetRoute
  '/api/feedback/nps': typeof ApiFeedbackNpsRoute
  '/api/feedback/pattern': typeof ApiFeedbackPatternRoute
  '/api/feedback/quality': typeof ApiFeedbackQualityRoute
  '/api/feedback/report': typeof ApiFeedbackReportRoute
  '/api/match/$id': typeof ApiMatchIdRoute
  '/api/referrals/claim': typeof ApiReferralsClaimRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/user/set-city': typeof ApiUserSetCityRoute
  '/api/venues/lookup': typeof ApiVenuesLookupRoute
  '/api/venues/onboard': typeof ApiVenuesOnboardRoute
  '/api/venues/track': typeof ApiVenuesTrackRoute
  '/api/auth/wechat/callback': typeof ApiAuthWechatCallbackRoute
  '/api/auth/wechat/start': typeof ApiAuthWechatStartRoute
  '/api/auth/wechat/unbind': typeof ApiAuthWechatUnbindRoute
  '/api/venues/merchant/dashboard': typeof ApiVenuesMerchantDashboardRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/founder': typeof FounderRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/match': typeof AuthenticatedMatchRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/api/authorize': typeof ApiAuthorizeRoute
  '/api/login': typeof ApiLoginRoute
  '/api/match': typeof ApiMatchRouteWithChildren
  '/api/referrals': typeof ApiReferralsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/auth/wx-callback': typeof AuthWxCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/match/$id': typeof AuthenticatedMatchIdRoute
  '/api/admin/reconciliation': typeof ApiAdminReconciliationRoute
  '/api/ai/generate-profile': typeof ApiAiGenerateProfileRoute
  '/api/ai/interview-questions': typeof ApiAiInterviewQuestionsRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/meet-plan': typeof ApiAiMeetPlanRoute
  '/api/cron/drain': typeof ApiCronDrainRoute
  '/api/cron/force-weekly-digest': typeof ApiCronForceWeeklyDigestRoute
  '/api/email/visit-confirm': typeof ApiEmailVisitConfirmRoute
  '/api/feedback/meet': typeof ApiFeedbackMeetRoute
  '/api/feedback/nps': typeof ApiFeedbackNpsRoute
  '/api/feedback/pattern': typeof ApiFeedbackPatternRoute
  '/api/feedback/quality': typeof ApiFeedbackQualityRoute
  '/api/feedback/report': typeof ApiFeedbackReportRoute
  '/api/match/$id': typeof ApiMatchIdRoute
  '/api/referrals/claim': typeof ApiReferralsClaimRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/user/set-city': typeof ApiUserSetCityRoute
  '/api/venues/lookup': typeof ApiVenuesLookupRoute
  '/api/venues/onboard': typeof ApiVenuesOnboardRoute
  '/api/venues/track': typeof ApiVenuesTrackRoute
  '/api/auth/wechat/callback': typeof ApiAuthWechatCallbackRoute
  '/api/auth/wechat/start': typeof ApiAuthWechatStartRoute
  '/api/auth/wechat/unbind': typeof ApiAuthWechatUnbindRoute
  '/api/venues/merchant/dashboard': typeof ApiVenuesMerchantDashboardRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/cookies'
    | '/dpa'
    | '/for-restaurants'
    | '/founder'
    | '/manifesto'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/match'
    | '/profile'
    | '/settings'
    | '/start'
    | '/api/authorize'
    | '/api/login'
    | '/api/match'
    | '/api/referrals'
    | '/api/stats'
    | '/api/waitlist'
    | '/auth/wx-callback'
    | '/blog/$slug'
    | '/match/$id'
    | '/api/admin/reconciliation'
    | '/api/ai/generate-profile'
    | '/api/ai/interview-questions'
    | '/api/ai/match'
    | '/api/ai/meet-plan'
    | '/api/cron/drain'
    | '/api/cron/force-weekly-digest'
    | '/api/email/visit-confirm'
    | '/api/feedback/meet'
    | '/api/feedback/nps'
    | '/api/feedback/pattern'
    | '/api/feedback/quality'
    | '/api/feedback/report'
    | '/api/match/$id'
    | '/api/referrals/claim'
    | '/api/user/me'
    | '/api/user/set-city'
    | '/api/venues/lookup'
    | '/api/venues/onboard'
    | '/api/venues/track'
    | '/api/auth/wechat/callback'
    | '/api/auth/wechat/start'
    | '/api/auth/wechat/unbind'
    | '/api/venues/merchant/dashboard'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/cookies'
    | '/dpa'
    | '/for-restaurants'
    | '/founder'
    | '/manifesto'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/match'
    | '/profile'
    | '/settings'
    | '/start'
    | '/api/authorize'
    | '/api/login'
    | '/api/match'
    | '/api/referrals'
    | '/api/stats'
    | '/api/waitlist'
    | '/auth/wx-callback'
    | '/blog/$slug'
    | '/match/$id'
    | '/api/admin/reconciliation'
    | '/api/ai/generate-profile'
    | '/api/ai/interview-questions'
    | '/api/ai/match'
    | '/api/ai/meet-plan'
    | '/api/cron/drain'
    | '/api/cron/force-weekly-digest'
    | '/api/email/visit-confirm'
    | '/api/feedback/meet'
    | '/api/feedback/nps'
    | '/api/feedback/pattern'
    | '/api/feedback/quality'
    | '/api/feedback/report'
    | '/api/match/$id'
    | '/api/referrals/claim'
    | '/api/user/me'
    | '/api/user/set-city'
    | '/api/venues/lookup'
    | '/api/venues/onboard'
    | '/api/venues/track'
    | '/api/auth/wechat/callback'
    | '/api/auth/wechat/start'
    | '/api/auth/wechat/unbind'
    | '/api/venues/merchant/dashboard'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/cookies'
    | '/dpa'
    | '/for-restaurants'
    | '/founder'
    | '/manifesto'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/_authenticated/match'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/start'
    | '/api/authorize'
    | '/api/login'
    | '/api/match'
    | '/api/referrals'
    | '/api/stats'
    | '/api/waitlist'
    | '/auth/wx-callback'
    | '/blog/$slug'
    | '/_authenticated/match/$id'
    | '/api/admin/reconciliation'
    | '/api/ai/generate-profile'
    | '/api/ai/interview-questions'
    | '/api/ai/match'
    | '/api/ai/meet-plan'
    | '/api/cron/drain'
    | '/api/cron/force-weekly-digest'
    | '/api/email/visit-confirm'
    | '/api/feedback/meet'
    | '/api/feedback/nps'
    | '/api/feedback/pattern'
    | '/api/feedback/quality'
    | '/api/feedback/report'
    | '/api/match/$id'
    | '/api/referrals/claim'
    | '/api/user/me'
    | '/api/user/set-city'
    | '/api/venues/lookup'
    | '/api/venues/onboard'
    | '/api/venues/track'
    | '/api/auth/wechat/callback'
    | '/api/auth/wechat/start'
    | '/api/auth/wechat/unbind'
    | '/api/venues/merchant/dashboard'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DpaRoute: typeof DpaRoute
  ForRestaurantsRoute: typeof ForRestaurantsRoute
  FounderRoute: typeof FounderRoute
  ManifestoRoute: typeof ManifestoRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ApiAuthorizeRoute: typeof ApiAuthorizeRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiMatchRoute: typeof ApiMatchRouteWithChildren
  ApiReferralsRoute: typeof ApiReferralsRouteWithChildren
  ApiStatsRoute: typeof ApiStatsRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiAdminReconciliationRoute: typeof ApiAdminReconciliationRoute
  ApiAiGenerateProfileRoute: typeof ApiAiGenerateProfileRoute
  ApiAiInterviewQuestionsRoute: typeof ApiAiInterviewQuestionsRoute
  ApiAiMatchRoute: typeof ApiAiMatchRoute
  ApiAiMeetPlanRoute: typeof ApiAiMeetPlanRoute
  ApiCronDrainRoute: typeof ApiCronDrainRoute
  ApiCronForceWeeklyDigestRoute: typeof ApiCronForceWeeklyDigestRoute
  ApiEmailVisitConfirmRoute: typeof ApiEmailVisitConfirmRoute
  ApiFeedbackMeetRoute: typeof ApiFeedbackMeetRoute
  ApiFeedbackNpsRoute: typeof ApiFeedbackNpsRoute
  ApiFeedbackPatternRoute: typeof ApiFeedbackPatternRoute
  ApiFeedbackQualityRoute: typeof ApiFeedbackQualityRoute
  ApiFeedbackReportRoute: typeof ApiFeedbackReportRoute
  ApiUserMeRoute: typeof ApiUserMeRoute
  ApiUserSetCityRoute: typeof ApiUserSetCityRoute
  ApiVenuesLookupRoute: typeof ApiVenuesLookupRoute
  ApiVenuesOnboardRoute: typeof ApiVenuesOnboardRoute
  ApiVenuesTrackRoute: typeof ApiVenuesTrackRoute
  ApiAuthWechatCallbackRoute: typeof ApiAuthWechatCallbackRoute
  ApiAuthWechatStartRoute: typeof ApiAuthWechatStartRoute
  ApiAuthWechatUnbindRoute: typeof ApiAuthWechatUnbindRoute
  ApiVenuesMerchantDashboardRoute: typeof ApiVenuesMerchantDashboardRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-restaurants': {
      id: '/for-restaurants'
      path: '/for-restaurants'
      fullPath: '/for-restaurants'
      preLoaderRoute: typeof ForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/wx-callback': {
      id: '/auth/wx-callback'
      path: '/wx-callback'
      fullPath: '/auth/wx-callback'
      preLoaderRoute: typeof AuthWxCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match': {
      id: '/api/match'
      path: '/api/match'
      fullPath: '/api/match'
      preLoaderRoute: typeof ApiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authorize': {
      id: '/api/authorize'
      path: '/api/authorize'
      fullPath: '/api/authorize'
      preLoaderRoute: typeof ApiAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/venues/track': {
      id: '/api/venues/track'
      path: '/api/venues/track'
      fullPath: '/api/venues/track'
      preLoaderRoute: typeof ApiVenuesTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/venues/onboard': {
      id: '/api/venues/onboard'
      path: '/api/venues/onboard'
      fullPath: '/api/venues/onboard'
      preLoaderRoute: typeof ApiVenuesOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/venues/lookup': {
      id: '/api/venues/lookup'
      path: '/api/venues/lookup'
      fullPath: '/api/venues/lookup'
      preLoaderRoute: typeof ApiVenuesLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/set-city': {
      id: '/api/user/set-city'
      path: '/api/user/set-city'
      fullPath: '/api/user/set-city'
      preLoaderRoute: typeof ApiUserSetCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/me': {
      id: '/api/user/me'
      path: '/api/user/me'
      fullPath: '/api/user/me'
      preLoaderRoute: typeof ApiUserMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals/claim': {
      id: '/api/referrals/claim'
      path: '/claim'
      fullPath: '/api/referrals/claim'
      preLoaderRoute: typeof ApiReferralsClaimRouteImport
      parentRoute: typeof ApiReferralsRoute
    }
    '/api/match/$id': {
      id: '/api/match/$id'
      path: '/$id'
      fullPath: '/api/match/$id'
      preLoaderRoute: typeof ApiMatchIdRouteImport
      parentRoute: typeof ApiMatchRoute
    }
    '/api/feedback/report': {
      id: '/api/feedback/report'
      path: '/api/feedback/report'
      fullPath: '/api/feedback/report'
      preLoaderRoute: typeof ApiFeedbackReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/quality': {
      id: '/api/feedback/quality'
      path: '/api/feedback/quality'
      fullPath: '/api/feedback/quality'
      preLoaderRoute: typeof ApiFeedbackQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/pattern': {
      id: '/api/feedback/pattern'
      path: '/api/feedback/pattern'
      fullPath: '/api/feedback/pattern'
      preLoaderRoute: typeof ApiFeedbackPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/nps': {
      id: '/api/feedback/nps'
      path: '/api/feedback/nps'
      fullPath: '/api/feedback/nps'
      preLoaderRoute: typeof ApiFeedbackNpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback/meet': {
      id: '/api/feedback/meet'
      path: '/api/feedback/meet'
      fullPath: '/api/feedback/meet'
      preLoaderRoute: typeof ApiFeedbackMeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/visit-confirm': {
      id: '/api/email/visit-confirm'
      path: '/api/email/visit-confirm'
      fullPath: '/api/email/visit-confirm'
      preLoaderRoute: typeof ApiEmailVisitConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/force-weekly-digest': {
      id: '/api/cron/force-weekly-digest'
      path: '/api/cron/force-weekly-digest'
      fullPath: '/api/cron/force-weekly-digest'
      preLoaderRoute: typeof ApiCronForceWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/drain': {
      id: '/api/cron/drain'
      path: '/api/cron/drain'
      fullPath: '/api/cron/drain'
      preLoaderRoute: typeof ApiCronDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/meet-plan': {
      id: '/api/ai/meet-plan'
      path: '/api/ai/meet-plan'
      fullPath: '/api/ai/meet-plan'
      preLoaderRoute: typeof ApiAiMeetPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/match': {
      id: '/api/ai/match'
      path: '/api/ai/match'
      fullPath: '/api/ai/match'
      preLoaderRoute: typeof ApiAiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/interview-questions': {
      id: '/api/ai/interview-questions'
      path: '/api/ai/interview-questions'
      fullPath: '/api/ai/interview-questions'
      preLoaderRoute: typeof ApiAiInterviewQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-profile': {
      id: '/api/ai/generate-profile'
      path: '/api/ai/generate-profile'
      fullPath: '/api/ai/generate-profile'
      preLoaderRoute: typeof ApiAiGenerateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reconciliation': {
      id: '/api/admin/reconciliation'
      path: '/api/admin/reconciliation'
      fullPath: '/api/admin/reconciliation'
      preLoaderRoute: typeof ApiAdminReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/match/$id': {
      id: '/_authenticated/match/$id'
      path: '/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof AuthenticatedMatchIdRouteImport
      parentRoute: typeof AuthenticatedMatchRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/venues/merchant/dashboard': {
      id: '/api/venues/merchant/dashboard'
      path: '/api/venues/merchant/dashboard'
      fullPath: '/api/venues/merchant/dashboard'
      preLoaderRoute: typeof ApiVenuesMerchantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/wechat/unbind': {
      id: '/api/auth/wechat/unbind'
      path: '/api/auth/wechat/unbind'
      fullPath: '/api/auth/wechat/unbind'
      preLoaderRoute: typeof ApiAuthWechatUnbindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/wechat/start': {
      id: '/api/auth/wechat/start'
      path: '/api/auth/wechat/start'
      fullPath: '/api/auth/wechat/start'
      preLoaderRoute: typeof ApiAuthWechatStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/wechat/callback': {
      id: '/api/auth/wechat/callback'
      path: '/api/auth/wechat/callback'
      fullPath: '/api/auth/wechat/callback'
      preLoaderRoute: typeof ApiAuthWechatCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMatchRouteChildren {
  AuthenticatedMatchIdRoute: typeof AuthenticatedMatchIdRoute
}

const AuthenticatedMatchRouteChildren: AuthenticatedMatchRouteChildren = {
  AuthenticatedMatchIdRoute: AuthenticatedMatchIdRoute,
}

const AuthenticatedMatchRouteWithChildren =
  AuthenticatedMatchRoute._addFileChildren(AuthenticatedMatchRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMatchRoute: AuthenticatedMatchRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthWxCallbackRoute: typeof AuthWxCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWxCallbackRoute: AuthWxCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ApiMatchRouteChildren {
  ApiMatchIdRoute: typeof ApiMatchIdRoute
}

const ApiMatchRouteChildren: ApiMatchRouteChildren = {
  ApiMatchIdRoute: ApiMatchIdRoute,
}

const ApiMatchRouteWithChildren = ApiMatchRoute._addFileChildren(
  ApiMatchRouteChildren,
)

interface ApiReferralsRouteChildren {
  ApiReferralsClaimRoute: typeof ApiReferralsClaimRoute
}

const ApiReferralsRouteChildren: ApiReferralsRouteChildren = {
  ApiReferralsClaimRoute: ApiReferralsClaimRoute,
}

const ApiReferralsRouteWithChildren = ApiReferralsRoute._addFileChildren(
  ApiReferralsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DpaRoute: DpaRoute,
  ForRestaurantsRoute: ForRestaurantsRoute,
  FounderRoute: FounderRoute,
  ManifestoRoute: ManifestoRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ApiAuthorizeRoute: ApiAuthorizeRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiMatchRoute: ApiMatchRouteWithChildren,
  ApiReferralsRoute: ApiReferralsRouteWithChildren,
  ApiStatsRoute: ApiStatsRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiAdminReconciliationRoute: ApiAdminReconciliationRoute,
  ApiAiGenerateProfileRoute: ApiAiGenerateProfileRoute,
  ApiAiInterviewQuestionsRoute: ApiAiInterviewQuestionsRoute,
  ApiAiMatchRoute: ApiAiMatchRoute,
  ApiAiMeetPlanRoute: ApiAiMeetPlanRoute,
  ApiCronDrainRoute: ApiCronDrainRoute,
  ApiCronForceWeeklyDigestRoute: ApiCronForceWeeklyDigestRoute,
  ApiEmailVisitConfirmRoute: ApiEmailVisitConfirmRoute,
  ApiFeedbackMeetRoute: ApiFeedbackMeetRoute,
  ApiFeedbackNpsRoute: ApiFeedbackNpsRoute,
  ApiFeedbackPatternRoute: ApiFeedbackPatternRoute,
  ApiFeedbackQualityRoute: ApiFeedbackQualityRoute,
  ApiFeedbackReportRoute: ApiFeedbackReportRoute,
  ApiUserMeRoute: ApiUserMeRoute,
  ApiUserSetCityRoute: ApiUserSetCityRoute,
  ApiVenuesLookupRoute: ApiVenuesLookupRoute,
  ApiVenuesOnboardRoute: ApiVenuesOnboardRoute,
  ApiVenuesTrackRoute: ApiVenuesTrackRoute,
  ApiAuthWechatCallbackRoute: ApiAuthWechatCallbackRoute,
  ApiAuthWechatStartRoute: ApiAuthWechatStartRoute,
  ApiAuthWechatUnbindRoute: ApiAuthWechatUnbindRoute,
  ApiVenuesMerchantDashboardRoute: ApiVenuesMerchantDashboardRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
