/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiAuthorizeRouteImport } from './routes/api/authorize'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as ApiUserMeRouteImport } from './routes/api/user/me'
import { Route as ApiAiMeetPlanRouteImport } from './routes/api/ai/meet-plan'
import { Route as ApiAiMatchRouteImport } from './routes/api/ai/match'
import { Route as ApiAiGenerateProfileRouteImport } from './routes/api/ai/generate-profile'
import { Route as AuthenticatedRateIdRouteImport } from './routes/_authenticated/rate.$id'
import { Route as AuthenticatedDateIdRouteImport } from './routes/_authenticated/date.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorizeRoute = ApiAuthorizeRouteImport.update({
  id: '/api/authorize',
  path: '/api/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiUserMeRoute = ApiUserMeRouteImport.update({
  id: '/api/user/me',
  path: '/api/user/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMeetPlanRoute = ApiAiMeetPlanRouteImport.update({
  id: '/api/ai/meet-plan',
  path: '/api/ai/meet-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMatchRoute = ApiAiMatchRouteImport.update({
  id: '/api/ai/match',
  path: '/api/ai/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateProfileRoute = ApiAiGenerateProfileRouteImport.update({
  id: '/api/ai/generate-profile',
  path: '/api/ai/generate-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRateIdRoute = AuthenticatedRateIdRouteImport.update({
  id: '/rate/$id',
  path: '/rate/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDateIdRoute = AuthenticatedDateIdRouteImport.update({
  id: '/date/$id',
  path: '/date/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/match': typeof AuthenticatedMatchRoute
  '/me': typeof AuthenticatedMeRoute
  '/start': typeof AuthenticatedStartRoute
  '/api/authorize': typeof ApiAuthorizeRoute
  '/api/login': typeof ApiLoginRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/date/$id': typeof AuthenticatedDateIdRoute
  '/rate/$id': typeof AuthenticatedRateIdRoute
  '/api/ai/generate-profile': typeof ApiAiGenerateProfileRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/meet-plan': typeof ApiAiMeetPlanRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/match': typeof AuthenticatedMatchRoute
  '/me': typeof AuthenticatedMeRoute
  '/start': typeof AuthenticatedStartRoute
  '/api/authorize': typeof ApiAuthorizeRoute
  '/api/login': typeof ApiLoginRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/date/$id': typeof AuthenticatedDateIdRoute
  '/rate/$id': typeof AuthenticatedRateIdRoute
  '/api/ai/generate-profile': typeof ApiAiGenerateProfileRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/meet-plan': typeof ApiAiMeetPlanRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/api/authorize': typeof ApiAuthorizeRoute
  '/api/login': typeof ApiLoginRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/_authenticated/date/$id': typeof AuthenticatedDateIdRoute
  '/_authenticated/rate/$id': typeof AuthenticatedRateIdRoute
  '/api/ai/generate-profile': typeof ApiAiGenerateProfileRoute
  '/api/ai/match': typeof ApiAiMatchRoute
  '/api/ai/meet-plan': typeof ApiAiMeetPlanRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/match'
    | '/me'
    | '/start'
    | '/api/authorize'
    | '/api/login'
    | '/api/stats'
    | '/api/waitlist'
    | '/date/$id'
    | '/rate/$id'
    | '/api/ai/generate-profile'
    | '/api/ai/match'
    | '/api/ai/meet-plan'
    | '/api/user/me'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/match'
    | '/me'
    | '/start'
    | '/api/authorize'
    | '/api/login'
    | '/api/stats'
    | '/api/waitlist'
    | '/date/$id'
    | '/rate/$id'
    | '/api/ai/generate-profile'
    | '/api/ai/match'
    | '/api/ai/meet-plan'
    | '/api/user/me'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/_authenticated/match'
    | '/_authenticated/me'
    | '/_authenticated/start'
    | '/api/authorize'
    | '/api/login'
    | '/api/stats'
    | '/api/waitlist'
    | '/_authenticated/date/$id'
    | '/_authenticated/rate/$id'
    | '/api/ai/generate-profile'
    | '/api/ai/match'
    | '/api/ai/meet-plan'
    | '/api/user/me'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  DpaRoute: typeof DpaRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ApiAuthorizeRoute: typeof ApiAuthorizeRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiAiGenerateProfileRoute: typeof ApiAiGenerateProfileRoute
  ApiAiMatchRoute: typeof ApiAiMatchRoute
  ApiAiMeetPlanRoute: typeof ApiAiMeetPlanRoute
  ApiUserMeRoute: typeof ApiUserMeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authorize': {
      id: '/api/authorize'
      path: '/api/authorize'
      fullPath: '/api/authorize'
      preLoaderRoute: typeof ApiAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/user/me': {
      id: '/api/user/me'
      path: '/api/user/me'
      fullPath: '/api/user/me'
      preLoaderRoute: typeof ApiUserMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/meet-plan': {
      id: '/api/ai/meet-plan'
      path: '/api/ai/meet-plan'
      fullPath: '/api/ai/meet-plan'
      preLoaderRoute: typeof ApiAiMeetPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/match': {
      id: '/api/ai/match'
      path: '/api/ai/match'
      fullPath: '/api/ai/match'
      preLoaderRoute: typeof ApiAiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-profile': {
      id: '/api/ai/generate-profile'
      path: '/api/ai/generate-profile'
      fullPath: '/api/ai/generate-profile'
      preLoaderRoute: typeof ApiAiGenerateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rate/$id': {
      id: '/_authenticated/rate/$id'
      path: '/rate/$id'
      fullPath: '/rate/$id'
      preLoaderRoute: typeof AuthenticatedRateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/date/$id': {
      id: '/_authenticated/date/$id'
      path: '/date/$id'
      fullPath: '/date/$id'
      preLoaderRoute: typeof AuthenticatedDateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
  AuthenticatedDateIdRoute: typeof AuthenticatedDateIdRoute
  AuthenticatedRateIdRoute: typeof AuthenticatedRateIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
  AuthenticatedDateIdRoute: AuthenticatedDateIdRoute,
  AuthenticatedRateIdRoute: AuthenticatedRateIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  DpaRoute: DpaRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ApiAuthorizeRoute: ApiAuthorizeRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiAiGenerateProfileRoute: ApiAiGenerateProfileRoute,
  ApiAiMatchRoute: ApiAiMatchRoute,
  ApiAiMeetPlanRoute: ApiAiMeetPlanRoute,
  ApiUserMeRoute: ApiUserMeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
